version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 777
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/install.sh
      runas: root
   Install:
    - location: scripts/start.sh
      runas: root
   AfterInstall:
    - location: scripts/restart.sh
      runas: root
